import {
  BadgeCheck,
  Boxes,
  Cpu,
  Factory,
  FileText,
  Gauge,
  PackageCheck,
  Ruler,
  ShieldCheck,
  Truck,
  Wrench,
} from "lucide-react";

export const company = {
  name: "Foshan City Huixun Metal CO., LTD.",
  tradingName: "Foshan Zhonghe Youpin Trading Co., Ltd.",
  email: "hx86.com@gmail.com",
  phone: "+86 159 8999 6985",
  whatsapp: "+86 159 8999 6985",
  address:
    "1st Floor, Workshop, No. 3, North of Cunbei Road, Xincun, Shang'an Community, Danzao Town, Nanhai District, Foshan City, China",
  tradingAddress:
    "No. 11-7, Shang'an No. 1 Industrial Zone, Danzao Town, Nanhai District, Foshan City",
};

export const products = [
  {
    slug: "5526-55mm-extruded-aluminum-heat-sink",
    title: "2.165 inch Wide Extruded Aluminum Heat Sink",
    shortTitle: "55 mm Extruded Heat Sink",
    productName: "Extruded Aluminum Heat Sink",
    model: "5526",
    width: "55 mm",
    inchWidth: "2.165 inch",
    image: "/assets/product-55.webp",
    photo: "/assets/product-55-detail.webp",
    weight: "1.75 kg/m",
    fins: "11 fins",
    finCount: "11 pcs fins",
    material: "Aluminum Alloy 6063-T5",
    oemOdm: "Available",
    surfaceTreatment: "Mill Finish (Non-Anodized) / Brushed Finish / Mirror Polished Finish / Anodized Finish",
    customSizes: "Available",
    testReport: "RoHS",
    cuttingTolerance: "+/-0.1 mm",
    holeTolerance: "+/-0.05 mm",
    summary:
      "Compact extruded aluminum heat sink profile for power modules, voltage regulators, MOSFETs, and small industrial control assemblies.",
    description:
      "This aluminum heat sink is designed to efficiently dissipate heat generated by high-power electronic devices, ensuring stable operation and extended service life of equipment. It is widely used in welding machines, audio amplifiers, air conditioners, inverters, and other industrial or electrical systems. With excellent thermal conductivity and reliable structural design, it provides effective cooling performance under continuous and high-load working conditions.",
    applications: ["Power modules", "MOSFET assemblies", "Voltage regulators", "Compact control boards"],
    highlights: ["Compact 55 mm footprint", "Drawing-based cut length", "OEM and ODM machining", "RoHS report available"],
  },
  {
    slug: "g7535-75mm-extruded-aluminum-heat-sink",
    title: "2.952 inch Wide Extruded Aluminum Heat Sink",
    shortTitle: "75 mm Extruded Heat Sink",
    productName: "Extruded Aluminum Heat Sink",
    model: "G-7535",
    width: "75 mm",
    inchWidth: "2.952 inch",
    image: "/assets/product-75.webp",
    photo: "/assets/product-75-detail.webp",
    weight: "2.046 kg/m",
    fins: "13 fins",
    finCount: "13 pcs fins",
    material: "Aluminum Alloy 6063-T5",
    oemOdm: "Available",
    surfaceTreatment: "Mill Finish (Non-Anodized) / Brushed Finish / Mirror Polished Finish / Anodized Finish",
    customSizes: "Available",
    testReport: "RoHS",
    cuttingTolerance: "+/-0.1 mm",
    holeTolerance: "+/-0.05 mm",
    summary:
      "Balanced mid-width extrusion for inverters, audio amplifiers, welding machine boards, and industrial electronics.",
    description:
      "This aluminum heat sink is designed to efficiently dissipate heat generated by high-power electronic devices, ensuring stable operation and extended service life of equipment. It is widely used in welding machines, audio amplifiers, air conditioners, inverters, and other industrial or electrical systems. With excellent thermal conductivity and reliable structural design, it provides effective cooling performance under continuous and high-load working conditions.",
    applications: ["Inverters", "Audio amplifiers", "Welding machines", "Industrial power boards"],
    highlights: ["13 fin thermal surface", "Stable profile for batch orders", "Multiple surface finishes", "Export carton packing"],
  },
  {
    slug: "g85x35-85mm-extruded-aluminum-heat-sink",
    title: "3.347 inch Wide Extruded Aluminum Heat Sink",
    shortTitle: "85 mm Extruded Heat Sink",
    productName: "Extruded Aluminum Heat Sink",
    model: "G-85X35",
    width: "85 mm",
    inchWidth: "3.347 inch",
    image: "/assets/product-85.webp",
    photo: "/assets/product-85-detail.webp",
    weight: "2.94 kg/m",
    fins: "11 fins",
    finCount: "11 pcs fins",
    material: "Aluminum Alloy 6063-T5",
    oemOdm: "Available",
    surfaceTreatment: "Mill Finish (Non-Anodized) / Brushed Finish / Mirror Polished Finish / Anodized Finish",
    customSizes: "Available",
    testReport: "RoHS",
    cuttingTolerance: "+/-0.1 mm",
    holeTolerance: "+/-0.05 mm",
    summary:
      "Wide profile with strong base mass for SCRs, rectifiers, power transistors, and heat-sensitive industrial drive systems.",
    description:
      "This aluminum heat sink is designed to efficiently dissipate heat generated by high-power electronic devices, ensuring stable operation and extended service life of equipment. It is widely used in welding machines, audio amplifiers, air conditioners, inverters, and other industrial or electrical systems. With excellent thermal conductivity and reliable structural design, it provides effective cooling performance under continuous and high-load working conditions.",
    applications: ["SCR assemblies", "Rectifiers", "Power transistors", "Industrial drives"],
    highlights: ["Wide 85 mm body", "Strong thermal mass", "CNC hole positioning", "Logo customization available"],
  },
  {
    slug: "g8540-85mm-high-fin-aluminum-heat-sink",
    title: "3.347 inch Wide Aluminum Heat Sink",
    shortTitle: "85 mm High-Fin Heat Sink",
    productName: "Extruded Aluminum Heat Sink",
    model: "G-8540",
    width: "85 mm",
    inchWidth: "3.347 inch",
    image: "/assets/product-g8540.webp",
    photo: "/assets/product-g8540-detail.webp",
    weight: "3.25 kg/m",
    fins: "22 fins",
    finCount: "22 pcs fins",
    material: "Aluminum Alloy 6063-T5",
    oemOdm: "Available",
    surfaceTreatment: "Mill Finish (Non-Anodized) / Brushed Finish / Mirror Polished Finish / Anodized Finish",
    customSizes: "Available",
    testReport: "RoHS",
    cuttingTolerance: "+/-0.1 mm",
    holeTolerance: "+/-0.05 mm",
    summary:
      "Dense fin design for programs that need more contact area under continuous high-load operating conditions.",
    description:
      "This aluminum heat sink is designed to efficiently dissipate heat generated by high-power electronic devices, ensuring stable operation and extended service life of equipment. It is widely used in welding machines, audio amplifiers, air conditioners, inverters, and other industrial or electrical systems. With excellent thermal conductivity and reliable structural design, it provides effective cooling performance under continuous and high-load working conditions.",
    applications: ["High-load electronics", "Power amplifiers", "Converters", "Control cabinets"],
    highlights: ["22 fin density", "High surface area", "Machined to drawing", "Suitable for long duty cycles"],
  },
  {
    slug: "sr-k002-100mm-extruded-aluminum-heat-sink",
    title: "3.937 inch Wide Extruded Aluminum Heat Sink",
    shortTitle: "100 mm Extruded Heat Sink",
    productName: "Extruded Aluminum Heat Sink",
    model: "SR-K002",
    width: "100 mm",
    inchWidth: "3.937 inch",
    image: "/assets/product-100.webp",
    photo: "/assets/product-100-detail.webp",
    weight: "2.533 kg/m",
    fins: "13 fins",
    finCount: "13 pcs fins",
    material: "Aluminum Alloy 6063-T5",
    oemOdm: "Available",
    surfaceTreatment: "Mill Finish (Non-Anodized) / Brushed Finish / Mirror Polished Finish / Anodized Finish",
    customSizes: "Available",
    testReport: "RoHS",
    cuttingTolerance: "+/-0.1 mm",
    holeTolerance: "+/-0.05 mm",
    summary:
      "Large 100 mm extrusion profile for converters, power supply housings, and custom assemblies requiring a broader mounting base.",
    description:
      "This aluminum heat sink is designed to efficiently dissipate heat generated by high-power electronic devices, ensuring stable operation and extended service life of equipment. It is widely used in welding machines, audio amplifiers, air conditioners, inverters, and other industrial or electrical systems. With excellent thermal conductivity and reliable structural design, it provides effective cooling performance under continuous and high-load working conditions.",
    applications: ["Large converters", "Power supply housings", "Custom assemblies", "High-power modules"],
    highlights: ["100 mm wide profile", "Broad mounting surface", "Sample before production", "Protected export shipment"],
  },
];

export const productFeatureTemplate = [
  "Made of high quality aluminum with good thermal conductivity.",
  "Reduces the risk of hardware failure caused by overheating.",
  "Maximizes the surface area in contact with cooling air.",
  "Designed for welding machines, inverters, computers, power transistors, FETs, ICs, power amplifiers, voltage regulators, MOSFETs, SCRs, and other electronic devices.",
  "Please confirm that the heat sink size and drawing match your application requirements before ordering.",
];

export const transportationStorage = [
  "Handle with care during transportation to avoid collision, extrusion, or surface damage.",
  "Store in a dry and ventilated environment. Avoid moisture, corrosive substances, and prolonged exposure to high temperatures.",
  "Keep the product in its original packaging before use to maintain surface quality and prevent oxidation.",
];

export const finishes = [
  "Mill finish",
  "Brushed finish",
  "Mirror polished finish",
  "Anodized finish",
  "Logo customization",
  "Custom carton packing",
];

export const capabilities = [
  { label: "Material", value: "6063-T5", note: "Aluminum alloy profile", icon: ShieldCheck },
  { label: "Cutting", value: "+/-0.1 mm", note: "Length controlled for batch orders", icon: Ruler },
  { label: "Hole position", value: "+/-0.05 mm", note: "Drawing-based machining", icon: Gauge },
  { label: "Custom work", value: "OEM / ODM", note: "Sizes, holes, logo, finish, packing", icon: Wrench },
];

export const factoryProof = [
  { title: "Profile stock", image: "/assets/factory-stock.webp", body: "Aluminum material prepared for cut-to-length heat sink orders." },
  { title: "Cutting and preparation", image: "/assets/factory-cutting.webp", body: "Profiles are cut, checked, and prepared for machining or finish." },
  { title: "Export loading", image: "/assets/factory-loading.webp", body: "Packed goods are protected for loading and international delivery." },
];

export const processSteps = [
  {
    step: "01",
    title: "Send drawings or requirements",
    body: "Share size, application, model, drawing, hole positions, surface finish, target quantity, and destination.",
    icon: FileText,
  },
  {
    step: "02",
    title: "Confirm technical details",
    body: "We review dimensions, machining, logo, packaging, sample needs, and shipping conditions before quote.",
    icon: BadgeCheck,
  },
  {
    step: "03",
    title: "Sample and production",
    body: "Samples can be arranged before mass production, then cutting, drilling, tapping, finishing, and inspection move together.",
    icon: Factory,
  },
  {
    step: "04",
    title: "Pack and ship",
    body: "Cartons are prepared to reduce collision, extrusion, oxidation, moisture, and surface damage during transport.",
    icon: Truck,
  },
];

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/products", label: "Products" },
  { href: "/about", label: "About" },
  { href: "/inquiry", label: "Inquiry" },
  { href: "/articles", label: "Articles" },
];

export const articleCards = [
  {
    slug: "custom-heat-sink-rfq-guide",
    title: "What to Prepare Before Requesting a Custom Aluminum Heat Sink Quote",
    category: "RFQ Guide",
    readTime: "5 min read",
    excerpt:
      "A practical checklist for dimensions, hole positions, application load, surface finish, quantity, and export packing.",
    image: "/assets/factory-cutting.webp",
  },
  {
    slug: "extruded-aluminum-heat-sink-fin-selection",
    title: "How Fin Count, Width, and Base Mass Affect Heat Sink Selection",
    category: "Engineering Notes",
    readTime: "6 min read",
    excerpt:
      "Use width, fin density, mounting area, and airflow conditions to narrow down the right extrusion profile.",
    image: "/assets/product-g8540-detail.webp",
  },
  {
    slug: "export-packing-for-machined-heat-sinks",
    title: "Export Packing Notes for Machined Aluminum Heat Sinks",
    category: "Export",
    readTime: "4 min read",
    excerpt:
      "Protecting brushed, polished, and anodized aluminum surfaces requires careful carton and handling planning.",
    image: "/assets/factory-shipment.webp",
  },
];

export const homeMetrics = [
  { label: "Profile widths", value: "55-100 mm", icon: Boxes },
  { label: "Core material", value: "6063-T5", icon: ShieldCheck },
  { label: "Buyer programs", value: "OEM / ODM", icon: Cpu },
  { label: "Shipment", value: "Export ready", icon: PackageCheck },
];
